image: ekino/docker-buildbox:node8.6-2017.11.01

stages:
  - build
  - deploy

build_site:
  stage: build
  artifacts:
    paths:
      - public/
  script:
    - npm install
    - npm run prod

deploy_site:
  stage: deploy
  dependencies:
    - build_site
  only:
    - master
  script:
    - echo "Script cannot be empty ;)"