image: ekino/docker-buildbox:node8.6-2017.11.01

stages:
  - build
  - deploy

build_site:
  stage: build
  script:
    - npm install
    - npm run prod
  artifacts:
    paths:
      - public

deploy_site:
  stage: deploy
  dependencies:
    - build_site
  only:
    - master
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public